# A docker compose file to start an Artemis AMQP broker
# more details on https://github.com/vromero/activemq-artemis-docker.
version: '2'

services:
  artemis-1-svc:
    image:  artemis-ubuntu:2.28.0
    ports:
      - "8160:8161"
      - "61616:61616"
      - "5670:5672"
    expose:
      - "61616"
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: artemis
  artemis-2-svc:
    image:  artemis-ubuntu:2.28.0
    ports:
      - "8161:8161"
      - "61617:61616"
      - "5672:5672"
    expose:
      - "61617"
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: artemis
 # bridge-svc:
 #   image: ru-kpip-demo-bridge:dev
 #   environment:
 #     kpip.bridge.concurrentConsumers: 10
 #     kpip.bridge.sourcePassword: artemis
 #     kpip.bridge.sourceQueue: ecm_queue.source
 #     kpip.bridge.sourceServer: tcp://127.0.0.1:61616
 #     kpip.bridge.sourceUser: artemis
 #     kpip.bridge.targetPassword: artemis
 #     kpip.bridge.targetQueue: ecm_queue.target
 #     kpip.bridge.targetServer: tcp://127.0.0.1:61617
 #     kpip.bridge.targetUser: artemis
 #   links:
 #     - artemis-1-svc
 #     - artemis-2-svc
 #   depends_on:
 #     - artemis-1-svc
 #     - artemis-2-svc